"""Jinja2 HTML report skeleton with QC / identity / projection slots."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

REPORT_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>GrapeAncestry Report — {{ sample }}</title>
<style>
  body { font-family: Georgia, serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #222; }
  h1 { font-size: 1.6rem; border-bottom: 2px solid #2f5d3a; padding-bottom: 0.3rem; }
  h2 { font-size: 1.2rem; color: #2f5d3a; margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1rem; }
  th, td { border: 1px solid #ccc; padding: 0.35rem 0.5rem; text-align: left; }
  th { background: #eef5ef; }
  .muted { color: #666; font-size: 0.9rem; }
</style>
</head>
<body>
<h1>GrapeAncestry Suite Report</h1>
<p class="muted">Sample: <strong>{{ sample }}</strong></p>

<h2>A — Capture QC</h2>
{% if qc %}
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  {% for k, v in qc.items() %}
  <tr><td>{{ k }}</td><td>{{ v }}</td></tr>
  {% endfor %}
</table>
{% else %}
<p class="muted">QC not run.</p>
{% endif %}

<h2>D — Identity (IBS nearest neighbors)</h2>
{% if identity %}
<table>
  <tr><th>Rank</th><th>Ref ID</th><th>IBS</th><th>Comparable sites</th></tr>
  {% for hit in identity %}
  <tr><td>{{ loop.index }}</td><td>{{ hit.ref_id }}</td><td>{{ '%.4f'|format(hit.ibs) }}</td><td>{{ hit.n_comparable }}</td></tr>
  {% endfor %}
</table>
{% else %}
<p class="muted">Identity not run.</p>
{% endif %}

<h2>B — Ancestry PCA projection</h2>
{% if projection %}
<table>
  <tr><th>PC</th><th>Value</th></tr>
  {% for i, v in projection %}
  <tr><td>PC{{ i }}</td><td>{{ '%.4f'|format(v) }}</td></tr>
  {% endfor %}
</table>
{% else %}
<p class="muted">Projection not run.</p>
{% endif %}

<h2>Appendix</h2>
<p class="muted">Generated by GrapeAncestry Suite. See docs/BUILD.md.</p>
</body>
</html>
"""


def render_report(
    sample: str,
    out_html: Path,
    qc: dict | None = None,
    identity: list | None = None,
    projection: list[tuple[int, float]] | None = None,
) -> Path:
    html = Template(REPORT_TMPL).render(
        sample=sample,
        qc=qc,
        identity=identity,
        projection=projection,
    )
    out_html.parent.mkdir(parents=True, exist_ok=True)
    out_html.write_text(html)
    return out_html
